dev:
    pnpm dev

build:
    pnpm build

start:
    pnpm start

typecheck:
    pnpm typecheck

lint:
    pnpm lint

format:
    pnpm fmt

format_check:
    pnpm fmt:check

db_generate:
    npx drizzle-kit generate

db_migrate:
    npx drizzle-kit migrate

db_studio:
    npx drizzle-kit studio

check: typecheck lint build
