dev:
    pnpm dev

build:
    pnpm build

start:
    pnpm start

typecheck:
    pnpm typecheck

lint:
    pnpm biome check .

format:
    pnpm biome format --write .

format_check:
    pnpm biome format --check .

db_generate:
    npx drizzle-kit generate

db_migrate:
    npx drizzle-kit migrate

db_studio:
    npx drizzle-kit studio

check: typecheck lint build
