'use server'

import { GetObjectCommand, S3Client } from '@aws-sdk/client-s3'
import { getSignedUrl } from '@aws-sdk/s3-request-presigner'
import { Resend } from 'resend'
import { env } from '~/lib/env'

const s3Client = new S3Client({
  region: 'auto',
  endpoint: `https://${env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com`,
  credentials: {
    accessKeyId: env.AWS_ACCESS_KEY_ID,
    secretAccessKey: env.AWS_SECRET_ACCESS_KEY,
  },
})

const resend = new Resend(env.RESEND_API_KEY)

export interface SendDeliveryEmailResult {
  success: boolean
  error?: string
}

/**
 * Generate a signed URL for downloading a file from R2
 * The URL expires after the specified number of days (default 7)
 */
export async function generateSignedDownloadUrl(
  objectKey: string,
  expiresInDays = 7,
): Promise<string> {
  const expiresInSeconds = expiresInDays * 24 * 60 * 60
  const command = new GetObjectCommand({
    Bucket: env.R2_BUCKET_NAME,
    Key: objectKey,
  })
  const signedUrl = await getSignedUrl(s3Client, command, { expiresIn: expiresInSeconds })
  return signedUrl
}

/**
 * Send delivery email with download link when order is complete
 */
export async function sendDeliveryEmail(
  orderId: number,
  email: string,
  styleName: string,
  outputPath: string,
): Promise<SendDeliveryEmailResult> {
  // Generate signed download URL (valid for 7 days)
  const downloadUrl = await generateSignedDownloadUrl(outputPath, 7)

  try {
    await resend.emails.send({
      from: 'Muse Frame <noreply@museframe.app>',
      to: email,
      subject: `Your Portrait "${styleName}" is Ready!`,
      html: `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <h1 style="color: #1a1a1a; text-align: center;">Your Portrait is Ready!</h1>
          <div style="background: #f5f5f5; border-radius: 12px; padding: 24px; margin: 24px 0;">
            <h2 style="color: #333; margin-top: 0;">${styleName}</h2>
            <p style="color: #666; font-size: 14px;">Order #${orderId}</p>
          </div>
          <p style="color: #1a1a1a; line-height: 1.6;">
            Great news! Your AI-generated portrait is ready for download.
          </p>
          <div style="text-align: center; margin: 32px 0;">
            <a href="${downloadUrl}"
               style="background: #000; color: #fff; padding: 14px 28px; border-radius: 8px; text-decoration: none; font-weight: 600; display: inline-block;">
              Download Your Portrait
            </a>
          </div>
          <p style="color: #888; font-size: 12px; text-align: center;">
            This download link will expire in 7 days.<br>
            A copy of this email has been sent to ${email}
          </p>
          <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;">
          <p style="color: #aaa; font-size: 11px; text-align: center;">
            Generated by Muse Frame • AI Personalized Portraits
          </p>
        </div>
      `,
    })

    console.log(`Delivery email sent for order ${orderId} to ${email}`)
    return { success: true }
  } catch (error) {
    console.error(`Failed to send delivery email for order ${orderId}:`, error)
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to send email',
    }
  }
}
